import hashlib
import json
from pathlib import Path

CONTRACT_PATH = Path("docs/CONTRACT_PACK.json")
OUTPUT_PATH = Path("src/contract/contract.generated.ts")


def main() -> None:
    if not CONTRACT_PATH.exists():
        raise SystemExit(f"Missing {CONTRACT_PATH}")

    raw = CONTRACT_PATH.read_bytes()
    contract_hash = hashlib.sha256(raw).hexdigest()
    payload = json.loads(raw.decode("utf-8"))

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    json_text = json.dumps(payload, ensure_ascii=True, indent=2)

    content = (
        "// This file is generated by scripts/generate-contract-types.py.\n"
        "// Do not edit by hand.\n"
        f"export const CONTRACT_HASH = \"{contract_hash}\";\n"
        f"export const contract = {json_text} as const;\n"
        "export type Contract = typeof contract;\n"
    )
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
